name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1

      - name: tofu fmt check
        run: tofu fmt -check -recursive

      - name: tofu init (module)
        run: tofu init -backend=false
        working-directory: modules/cluster

      - name: tofu validate (module)
        run: tofu validate
        working-directory: modules/cluster

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: terraform-module
